### ISSUE TITLE
Cannot find module 'C:\bin\www'

### ISSUE THREAD

**Issue by dotku** [expressjs/generator#101]
I run `npm start`, and I got the error like this...

> Cannot find module 'C:\bin\www'

Well, It will run by `node bin/www`, but it is not the way on the manual...

> via http://expressjs.com/en/starter/generator.html
> 
> On Windows, use this command:
> \>set DEBUG=myapp:* & npm start

**Comment by dougwilson** [comment]
Hi @dotku, what version of this generator are you using? You can run `express --version` to determine that.

**Comment by dotku** [comment]
@dougwilson I'm using version 4.13.1

> $ express --version
> 4.13.1

**Comment by frota** [comment]
Are you using `"start": "node /bin/www"` instead of  `"start": "node ./bin/www"` (with a dot) in your package.json file?

**Comment by tauhidul0821** [comment]
i change root folder name then i fetch this type of problem so  
1.open file  bin/www
2.var debug = require('debug')('your_root_folder_name:server'); 
3. open cmd on root folder and set DEBUG 
3.set DEBUG=your_new_directory:* & npm start
