### ISSUE TITLE
404 for "Should I check my node_modules folder into git" link in generated gitignore

### ISSUE THREAD

**Issue by nicolasmccurdy** [expressjs/generator#108]
https://www.npmjs.org/doc/misc/npm-faq.html#should-i-check-my-node_modules-folder-into-git- in the [generated gitignore](https://github.com/expressjs/generator/blob/b313f3ba2779b9935212d204c3066be83a3aeab9/templates/js/gitignore#L26) is a 404 (with and without the trailing `-`).

**Comment by dougwilson** [comment]
Thanks for letting us know! I wonder where they moved their FAQ document to. If anyone knows where that section went in their docs, let us know :)

**Comment by nicolasmccurdy** [comment]
I was trying to find it but I'm not sure, it seems like they've moved stuff around. I'll let you know if I figure it out.

**Comment by nicolasmccurdy** [comment]
Since npm already recommended ignoring node_modules in most cases, I think we should remove the broken link and recommend the use of `npm shrinkwrap` for stricter version matching.

**Comment by dougwilson** [comment]
That's not completely true. That FAQ was about when it makes sense to check in your node modules, hence why it was in the gitignore. We can just remove the link, but only if that documentation is actually removed from their site, and not just shuffled around.
