### ISSUE TITLE
Jade has been renamed Pug

### ISSUE THREAD

**Issue by dmsakamoto** [expressjs/generator#109]
Update Jade to Pug. Jade has been deprecated
![screen shot 2016-04-13 at 7 09 35 pm](https://cloud.githubusercontent.com/assets/1882429/14515087/507cb548-01ab-11e6-8d51-e1c17030f933.png)

**Comment by tunniclm** [comment]
There is a pull request open for this: https://github.com/expressjs/generator/pull/107

**Comment by UndergroundLabs** [comment]
Same error. Has this been fixed yet?

**Express version:** 4.13.1

    npm WARN deprecated jade@1.11.0: Jade has been renamed to pug, please install the latest version of pug instead of jade
    npm WARN deprecated transformers@2.1.0: Deprecated, use jstransformer
