### ISSUE TITLE
express: command not found

### ISSUE THREAD

**Issue by hwbrill** [expressjs/generator#111]
Output I get when I try to display the command options by:
$ express -h
Please refer to the web page: http://expressjs.com/en/starter/generator.html

**Comment by gokaygurcan** [comment]
Could you please paste the output of `which express` ?

**Comment by hwbrill** [comment]
@gokaygurcan , yesterday the $ npm install -g express-generator  installed it in my /usr/local/Cellar/node/6.0.0/... -> /usr/local/Cellar...
Every time I tried to verify the link by the $ express -h command  the output was express: command not found
I believe it was version 4.13.1
Now, it installed correctly...
only difference... node version went from 6.0.0 to 6.1.0...

$ npm install -g express-generator
/usr/local/bin/express -> /usr/local/lib/node_modules/express-generator/bin/express
/usr/local/lib
└─┬ express-generator@4.13.1 
  ├─┬ commander@2.7.1 
  │ └── graceful-readlink@1.0.1 
  ├─┬ mkdirp@0.5.1 
  │ └── minimist@0.0.8 
  └── sorted-object@1.0.0 

Herbs-iMac:~ hwbrill$ express -h

  Usage: express [options] [dir]

  Options:

    -h, --help          output usage information
    -V, --version       output the version number
    -e, --ejs           add ejs engine support (defaults to jade)
        --hbs           add handlebars engine support
    -H, --hogan         add hogan.js engine support
    -c, --css <engine>  add stylesheet <engine> support (less|stylus|compass|sass) (defaults to plain css)
        --git           add .gitignore
    -f, --force         force on non-empty directory
I did an brew upgrade and then brew cleanup but didn't try the $ npm install -g express-generator until your comment...
FYI...

**Comment by dougwilson** [comment]
Hi @hwbrill it sounds like you got it working :) I hope it's OK if I close this issue now :) With it working, it will be hard to figure out what the issue was, but I would suspect that perhaps the bin was being installed in a directory not in the `$PATH` by npm and by doing the `brew` command, it updated your `$PATH`.

**Comment by ChanForPres** [comment]
Have similar issue, running brew upgrade now
