### ISSUE TITLE
Change from jade to pug

### ISSUE THREAD

**Issue by bardiharborow** [expressjs/generator#113]
Refer to pugjs/pug#2184

**Comment by dougwilson** [comment]
Not until pug it at least stable. There have been many alpha and now beta releases, with the API shifting every so often. See https://github.com/pugjs/pug/issues/2405 .

If anything, if there is no stable pug before express 4.14, then maybe we will add pug as a secondary option, not replace jade.

**Comment by bardiharborow** [comment]
As long as it's being tracked. :)

**Comment by dougwilson** [comment]
Yes. There have been a few issues and PRs here already. There is even an open PR that we are just waiting on a stable pug to merge.
