### ISSUE TITLE
Jade has been renamed to pug

### ISSUE THREAD

**Issue by w1ndy** [expressjs/generator#114]
Using default generation settings and running ``npm install`` raise a warning:

```
[jade@1.11.0](./node_modules/jade) deprecate: Jade has been renamed to pug, please install the latest version of pug instead of jade
```

**Comment by dougwilson** [comment]
Yep, and there are PRs for this already; `pug` is still in beta and not completely compatible and keeps changing how it works, so we cannot adopt it until it's at least stable. Yes, it sucks that `jade` was marked deprecated without any reliable replacement.
