### ISSUE TITLE
a small issue

### ISSUE THREAD

**Issue by orafaelreis** [expressjs/generator#129]
I would like to see at command line what port the service is running after "npm start"

**Comment by dougwilson** [comment]
After generating your app, the instructions show you what command to run which will print that port number to the screen. The command depends on your OS and the name of your app.

**Comment by orafaelreis** [comment]
Thank you for answer but I will go on with express without generator. I don't think it's easy to understand it at this time.

**Comment by dougwilson** [comment]
Sure thing! Always feel free to let us know how you think we can improve things, add to documentation, etc.! A lot of time, there is a disconnect where it's hard for us to understand the reasons why a user is confused and how exactly we can change things to help.

At least in this case, we created the generator to print to the console when you generated the app the exact command you should run to start the server, which prints (even with colors) the port number the server is running on, so I just don't quite understand how we can improve the experience.
