### ISSUE TITLE
Default template engine is still Jade, rather than Pug

### ISSUE THREAD

**Issue by stuartellis** [expressjs/generator#133]
By default, the current release generates projects with Jade, rather than the replacement, Pug. This is a legal (copyright) issue, more than a technical one:

https://github.com/pugjs/pug/issues/2184

**Comment by dcollao** [comment]
![image](https://cloud.githubusercontent.com/assets/20039386/18341898/9d9f8ba2-7582-11e6-8ccf-f86749b82b86.png)

**Comment by blakeembrey** [comment]
I've seen this issue logged every other week. Please search for existing issues before opening another one. E.g. https://github.com/expressjs/generator/issues?q=is%3Aissue+jade+is%3Aclosed, there's a couple of already closed issues with descriptions.
