### ISSUE TITLE
Add pug engine (as default or as option)

### ISSUE THREAD

**Issue by tornordqvist** [expressjs/generator#136]
Pug has replaced jade, so shouldn't the generator file be updated for this?

Changing program.template = 'pug' and rename the views-files to *.pug?

**Comment by dougwilson** [comment]
The 4.14 branch, which is the next pending release, already adds support for pug. As for changing the default from jade to pug, that's an option that has been discussed at length and the current answer is we really just can't consider it until a non-alpha/beta (i.e. stable) release of pug is made to even depend on.
