### ISSUE TITLE
what's the port number to run on?

### ISSUE THREAD

**Issue by luckypoem** [expressjs/generator#139]
hi.

root@AR:/usr/local/express-site# ls
app.js	bin  node_modules  package.json  public  routes  views
root@AR:/usr/local/express-site# npm start

> express-site@0.0.0 start /usr/local/express-site
> node ./bin/www

i should visit http://my_vps_ip:which_port_number?

**Comment by Velua** [comment]
**3000** by default, which can be changed in bin/www file line 15.

**Comment by gokaygurcan** [comment]
@Velua, your answer is true but not complete. 

```javascript
var port = normalizePort(process.env.PORT || '3000');
app.set('port', port);
```

This was copied from `./bin/www`, so you have three options here: 
- using 3000, which is default
- changing the number in file
- using an argument. 

For the last option, start your app like this:
`PORT=1234 node ./bin/www`

**Comment by dougwilson** [comment]
Hi @luckypoem I hope you got your answer above :) I added a little extra documentation around this on the 4.14 branch, but if anyone wants to make a PR for additional documentation, you're more than welcome :) !
