### ISSUE TITLE
Express generator: package.json name cannot have spaces

### ISSUE THREAD

**Issue by segrey** [expressjs/generator#143]
Generator uses current directory by default as application name (https://github.com/expressjs/generator/blob/v4.13.4/bin/express#L328) and sets "name" value in package.json accordingly. It might so happen that the name will contain spaces (if current directory name contained spaces). That will break the npm rule (https://docs.npmjs.com/files/package.json):
>Therefore, the name can't contain any non-URL-safe characters

Related discussion in npm: https://github.com/npm/npm/issues/3105
How about replacing space with some other character, e.g. dash `-`?

**Comment by dougwilson** [comment]
Great idea! We can use `validate-npm-package-name` to validate the name, and the README there lists all the specific rules. I looked around a bit to see if there was a module by the npm team we could use to generate the name, but there isn't one I can find. So we can probably do a couple simple transformations, and if it doesn't pass `validate-npm-package-name`, then prompt for the name.

**Comment by gokaygurcan** [comment]
Why not just slugify the name and use the slug?

**Comment by dougwilson** [comment]
Yep, @gokaygurcan , sligufying would be fine, and I would count that as the "do a couple simple transformations" in my thoughts above. So: we can probably slugify the directory name, and if it doesn't pass validate-npm-package-name, then prompt for the name.

**Comment by dougwilson** [comment]
I added a fix in the 4.14 release proposal for this. You can see it in commit https://github.com/expressjs/generator/commit/180ec56c3d36af4c8f9e6817a064231827abba8b
