### ISSUE TITLE
Using webpack to build for production

### ISSUE THREAD

**Issue by andlcool** [expressjs/generator#151]
Hi there,

I am exploring using webpack to bundle the application before deploying to production. Is it possible to use webpack as part of build and anyone has a guide to do that. I tried searching around and there was no resources on this topic. I also tried to play around with webpack but hits a lot errors.

Thanks.

**Comment by dougwilson** [comment]
Hi @andlcool I'm sorry I don't know and it doesn't seem like anyone else who has stopped by knows the answer from the lack of response. You may be able to get an answer on the support forum for Express: https://gitter.im/expressjs/express
