### ISSUE TITLE
Option for no view engine

### ISSUE THREAD

**Issue by tobymurray** [expressjs/generator#152]
With the wealth of front end frameworks available now, I don't find it appealing to use any of the view engines, though bootstrapping technologies like this project appeal to me. My use case is as follows:

- Angular front end transpiled/compiled/obfuscated/minified/whatever into a bunch of static blobs
- Nginx delivering the client (bunch of static blobs)
- Express providing the API for the client and all the other goodness.

What are your thoughts on providing another flag (e.g. --view none) to avoid the view engine entirely? Perhaps if the same "plug-and-play" experience is desired the routes could serve up regular old HTML files from the public folder? 

I can take a stab at adding it if it's viable.

**Comment by dougwilson** [comment]
I think that is a good idea.

**Comment by tobymurray** [comment]
I think I've got something close to working, but it's just a tiny bit awkward because "none" is different than every other view engine - e.g. the `// view engine setup` section doesn't need to be there. Looking at #141 - what are your thoughts about defaulting to no view engine? I think conceptually it makes sense, but it's definitely a change from the status quo.

**Comment by dougwilson** [comment]
Yea, defaulting is certainly a discussion, but we can add it even without it being the default. A few PRs tried this previously, but got abandoned. The called it "static" instead of none, which is probably a good name for the engine.
