### ISSUE TITLE
How to omit creation of a new package.json?

### ISSUE THREAD

**Issue by wzup** [expressjs/generator#159]
Is there options for command line that make `express-generator` not to create a brand new `package.json`? Because I already have one. And `express myapp` will override it, deletes and creates a new one.

**Comment by dougwilson** [comment]
There is no option for that currently.

**Comment by LoganDark** [comment]
```
mv package.json package.json.bak
(...)
mv package.json.bak package.json
```

**Comment by dougwilson** [comment]
So far in the year of this issue there was one pull request that the author abandoned and deleted. It doesn't seem like there is a large demand here, but if someone does make a pull request, we can certainly take a look!
