### ISSUE TITLE
Usability issues with help text

### ISSUE THREAD

**Issue by robrich** [expressjs/generator#164]
I had the opportunity to watch a new user use this today, and the experience was incredibly enlightening.

1. Help says `express-cli [options] [dir]`.  This immediately confused the user as he just typed `express -h`, so he typed `express-cli -h` which didn't work.  This is because commander doesn't know the file is renamed as it's moved from the project's `bin/express-cli.js` to `node_modules/.bin/express` during install.  We should consider renaming `express-cli.js` to `express.js` to avoid this.

2. There was great confusion between "express generator" with the command line of `express` and the web server "express" with `require('express')`.  Not sure what we can do here, but I call it out merely because he was confused.

3. Help first lists `--ejs` and `--hbs` then lists `--view <engine>` much further down the list.  The user typed `express --hbs .`  It did the task, but noted that `--hbs` was deprecated in favor of `--view hbs`.  Immediately the user asked what he did wrong, and then quickly turned the aggression to "out of date docs".  I think if `--ejs` and `--hbs` and `--pug` are indeed deprecated, we should remove them from the help output, put them at the end of the list, and/or note they're deprecated in the help text.  Alternatively, if they're just aliases to the same tasks, let's not show the deprecation message.

4. It surprised the user that the deprecation warning hit but that it did the task anyway.  Perhaps we can improve the message to note the task was completed successfully, but there's a better way to do it next time.

**Comment by dougwilson** [comment]
This is great, feedback! Sounds like a lot of low-hanging fruit, too, so I'm going to mark this as "good first contribution" to help people who want to become involved in the project a good way to get in.

For those coming from the tags: I would suggest that really these 4 separate issues should get split into 4 new issues, so they can be individually discussed and tracked, so we don't risk missing anything. Ideally if you think of a possible solution to address the item, feel free to lay out the possible solution in an issue before proceeding to a pull request, though if you feel more comfortable starting with a pull request, we'll work with that as well :)

**Comment by vikramnr** [comment]
@dougwilson So Four Issues has be to created and raise PR's for the same?

**Comment by dougwilson** [comment]
Hi @vikramnr yea, I would suggest that really these 4 separate issues should get split into 4 new issues, so they can be individually discussed and tracked, so we don't risk missing anything. Even if you decide to take on all four, trying to land all four things at once in a single pull request usually is not very successful, as say 3 of the 4 are good, but there is a lot of back and forth on the 4th one, it prevents the 3 good ones from ever landing, since it's just one pull request. It can also cause a lot of confusion when multiple topics are getting discussed in the same issue / pull request.
