### ISSUE TITLE
why everybody work like a dinosaur ? no ES6/ES7

### ISSUE THREAD

**Issue by webmobiles** [expressjs/generator#171]
everybody is working for very old node versions? just a few packages like create-react-app create a nice skeleton to work with modern javascript.
I've got pain on the eyes when i see 'ar, require ,etc,  and i feel like a dionsaur, 
I came from php world the big dinosaur , but really feel same on the node packages world

Is for compatibility maintain all in old javascript?

**Comment by dougwilson** [comment]
Hi @webmobiles there is currently a pull request with a user working to add this support. You're welcome to help out!

**Comment by webmobiles** [comment]
yes, i'd like to help, how to start ?

**Comment by dougwilson** [comment]
Probably comment on that pull request to ask the author how you can help.
