### ISSUE TITLE
Broken README section

### ISSUE THREAD

**Issue by JamesYFC** [expressjs/generator#172]
https://github.com/expressjs/generator/commit/c53f6f2bfc52dfc74128db10c2a1a4dac3abd5fb breaks the command line args section in the README.

[see diff](https://github.com/expressjs/generator/commit/c53f6f2bfc52dfc74128db10c2a1a4dac3abd5fb#diff-04c6e90faac2675aa89e2176d2eec7d8)

**Comment by dougwilson** [comment]
oops, looks like it was copy of some terminal wrap. Thanks for spotting! You're always welcome to make a PR as well :) !
