### ISSUE TITLE
nodemon issue

### ISSUE THREAD

**Issue by snigdharedd** [expressjs/generator#178]
i am facing the issue with nodemon

$ nodemon
[nodemon] 1.12.1
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: *.*
[nodemon] starting `node app.js`
[nodemon] clean exit - waiting for changes before restart

**Comment by joewagner** [comment]
@snigdharedd I'm not sure how you've used express-generator but the default entry point is `bin/www`, not `app.js`

**Comment by gasp** [comment]
if you are using pug and sass, the command should be `$nodemon -e js,pug,scss bin/www `

**Comment by dougwilson** [comment]
Let us know if that didn't work and we can reopen!
