### ISSUE TITLE
Dependency with known vulnerabilities

### ISSUE THREAD

**Issue by michaelhidalgo** [expressjs/generator#179]
Hi there,
It seems like latest version of express-generator (4.15.5), creates a scaffolding with a dependency that has a known vulnerability in the dependency chain. The vulnerability seems to be a Regular Expression Denial of Service (ReDos) https://nodesecurity.io/advisories/535

The dependency seems to be here:

express@4.15.5 -> send@0.15.6 -> mime@1.3.4  

<img width="1210" alt="screen shot 2017-11-16 at 8 33 33 pm" src="https://user-images.githubusercontent.com/1732035/32926630-da128a1c-cb0d-11e7-8a81-5a46c5c74803.png">

**Comment by dougwilson** [comment]
Thanks for the report! Fix is pending release in #173 already 👍 The `mime` dependency doesn't actually introduce a vulnerability, see the announcement https://github.com/expressjs/express/issues/3431
