### ISSUE TITLE
How about synchronize .gitignore with github/gitignore?

### ISSUE THREAD

**Issue by marswong** [expressjs/generator#181]
it seems better to use [github/gitignore](https://github.com/github/gitignore/blob/master/Node.gitignore)

**Comment by dougwilson** [comment]
That is exactly what it already uses 👍

**Comment by marswong** [comment]
@dougwilson oh noap, i mean synchronize dynamically when generating `.gitignore`, as u see, the [templates/js/gitignore](https://github.com/expressjs/generator/blob/master/templates/js/gitignore) is outdated at present :)

**Comment by dougwilson** [comment]
Ah, gotcha. Please make a PR to implement what you're suggesting :+1:
