### ISSUE TITLE
Can't generate express app with node-sass-middleware=0.9.8

### ISSUE THREAD

**Issue by hondasmx** [expressjs/generator#189]
1. Generate project with css engine SASS (express --view=pug --css=sass)
2. Run npm install
3. Get an error
Downloading binary from https://github.com/sass/node-sass/releases/download/v3.13.1/darwin-x64-57_binding.node
Cannot download "https://github.com/sass/node-sass/releases/download/v3.13.1/darwin-x64-57_binding.node": 

HTTP error 404 Not Found

There is no error if node-sass-middleware=0.11.0

**Comment by dougwilson** [comment]
Thanks for reporting! We got the change pending in the next release of the generator already: #173 👍
