### ISSUE TITLE
Server listens on port already in use

### ISSUE THREAD

**Issue by bacrossland** [expressjs/generator#206]
If that port is already in use by another application when ```npm start``` is run, the server fails to err and starts up as if the port is free to listen on.

The issue is related to the server configuration for events happening after the listen call is made and the listen call not specifying a binding of 0.0.0.0.

**Comment by dougwilson** [comment]
Thanks for the report! It looks like you opened a pull request, so there is no action to take on this issue, closing. If there is an action we should take on this issue, let me know what it is and I can reopen :+1:
