### ISSUE TITLE
Question: why does onError handler only handle "listen" errors?

### ISSUE THREAD

**Issue by lonix1** [expressjs/generator#224]
The template defines an `onError()` [event handler](https://github.com/expressjs/generator/blob/master/templates/js/www.ejs#L57) that has this:

    if (error.syscall !== 'listen') throw error;

The `syscall` is described as "[a string describing the syscall that failed](https://nodejs.org/api/errors.html#errors_error_syscall)", of which there are [many possible types of failures](http://man7.org/linux/man-pages/man2/syscalls.2.html) (on linux, not sure what would happen on windows).

So why is only a "listen" error handled - surely the node app can fail for other reasons?

**Comment by dougwilson** [comment]
Other errors just bubble up and that line will just have Node.js print out the error with a stack trace. Only the listen errors have human readable messages. If you know of other errors that can have human readable messages, please feel free to make a pr to add it :)

**Comment by lonix1** [comment]
I'm not sure what you mean by human readable messages? Are you saying that if `syscall !== "listen"` then `error.code` won't be `"EACCESS"` or `"EADDRINUSE"`, etc.?

**Comment by dave-kennedy** [comment]
To answer this question, we have to look at the rest of the function:

```javascript
function onError(error) {
  if (error.syscall !== 'listen') {
    throw error;
  }

  var bind = typeof port === 'string'
    ? 'Pipe ' + port
    : 'Port ' + port;

  // handle specific listen errors with friendly messages
  switch (error.code) {
    case 'EACCES':
      console.error(bind + ' requires elevated privileges');
      process.exit(1);
      break;
    case 'EADDRINUSE':
      console.error(bind + ' is already in use');
      process.exit(1);
      break;
    default:
      throw error;
  }
}
```

Only errors of type 'EACCES' or 'EADDRINUSE' get special handling. Every other type of error is just thrown. Those error types will only ever coincide with `error.syscall === 'listen'`. So, if that condition isn't true, might as well throw it and exit early. It's a form of guard clause which aids readability.
