### ISSUE TITLE
Add ECMAScript Modules support

### ISSUE THREAD

**Issue by gfeller** [expressjs/generator#231]
Any plans for supporting ECMAScript Modules?

**Comment by ryhinchey** [comment]
Is the idea that a transpilation step with Babel would also be included in the generator for this?  

Given the versions of node that Express needs to support, I don't see es module support being added to express or this generator without an included transpilation step (which greatly increases the complexity of adding es module support).

That said, PRs are always welcome.

**Comment by dougwilson** [comment]
The age of this issue and no elaboration of what, exactly the feature should look like makes this not very actionable by us. If someone wants to provide enough details for someone to work on this, it can be reopened.
