### ISSUE TITLE
Support for Vue.js

### ISSUE THREAD

**Issue by slidenerd** [expressjs/generator#238]
Surely you guys have heard of Vue.js
It would be amazing if you can add option support for pug|esj|hb|vue so that selecting vue can attach directly to .Vue files using the template style syntax

**Comment by ryhinchey** [comment]
There's a similar issue https://github.com/expressjs/generator/issues/251 related to React/JSX support.  The suggestion is to use this [middleware](https://github.com/reactjs/express-react-views) which is well supported by core React folk.  That middleware (per their docs) `renders static markup and does not support mounting those views on the client.`.

Does Vue  have a similar option where you're only using it as a templating language with no need for client-side Vue.js?
