### ISSUE TITLE
customizable static folders' names

### ISSUE THREAD

**Issue by revaxl** [expressjs/generator#239]
First, I like to say that I do love this generator because it really comes handy when I'm trying to work on side projects and testing things out.

Now for the thing I'm asking, is it possible to make the static folders' names customizable to my own style, reason is I don't like the default naming "stylesheets, images, javascripts" because I usually go something short like "css" or "js" or "img".

I believe I might be able to create this and do a PR, if of course this is kinda useful.

Note: if I change the names of those folders then I can to change them also in the template which will probably result if more refactoring than just the cli file 

thank you for your consideration.

**Comment by ryhinchey** [comment]
> Note: if I change the names of those folders then I can to change them also in the template which will probably result if more refactoring than just the cli file

I don't believe the names should be changed in the template for personal preference.  Having the full name `javascripts`, `images`, etc at least make it explicitly clear what the folders are for (vs `js`, `img`, etc).  

There's currently a concise list of [command line options](https://github.com/expressjs/generator#command-line-options) and I'm not sure adding to that list to _just_ rename something is worth it.  That said, if you're interested in making a PR - go for it!

**Comment by ryhinchey** [comment]
I'm going to go ahead and close this issue.  Feel free to raise a PR with more semantic naming conventions if you'd like!
