### ISSUE TITLE
"found 1 high severity vulnerability"

### ISSUE THREAD

**Issue by Drozerah** [expressjs/generator#240]
`hbs` dependency is outdated `npm audit` returns 1 high severity vulnerability, see the advisory 

https://www.npmjs.com/advisories/1164

**Comment by dougwilson** [comment]
Run npm update.

**Comment by zrrtcs** [comment]
related issue:
https://github.com/pillarjs/hbs/issues/185

**Comment by w3bdesign** [comment]
Also try "npm update -g" if it is globally installed.
