### ISSUE TITLE
Only build, test and support still supported Node.js versions

### ISSUE THREAD

**Issue by danielkhan** [expressjs/generator#241]
I think we should update the CI configuration and package.json to just include versions that are currently still supported.
Right now this project supports everything until back to 0.10.

![Node.js Support Matrix](
https://github.com/nodejs/Release/raw/master/schedule.svg?sanitize=true)

**Comment by dougwilson** [comment]
Correct, the generator supports the same versions of Node.js as the related Express versions it generates for. When Express launches with updated Node.js versions the generator will also match it.
