### ISSUE TITLE
why do you need to store the port in express if you later set the port from var

### ISSUE THREAD

**Issue by ionutale** [expressjs/generator#255]
https://github.com/expressjs/generator/blob/d1f3fcc6ccc7ab8986fb3438c82ab1a1f20dc50d/templates/js/www.ejs#L16

/**
 * Get port from environment and store in Express.
 */

var port = normalizePort(process.env.PORT || '3000');
app.set('port', port);

/**
 * Create HTTP server.
 */

var server = http.createServer(app);

/**
 * Listen on provided port, on all network interfaces.
 */

server.listen(port);
server.on('error', onError);
server.on('listening', onListening);

please explain

**Comment by dougwilson** [comment]
It is stored in a variable as it is used in multiple places in the file.

**Comment by dougwilson** [comment]
As for storing in on express as a setting, it is not necessary, but a common convention to get the port in your other files with `app.get('port')`
