### ISSUE TITLE
jade is deprecated and has vulnerable dependencies. bump to use pug instead

### ISSUE THREAD

**Issue by jilvin** [expressjs/generator#257]
Seems pretty critical. Adding an issue in case it was not noted yet.

**Comment by jilvin** [comment]
on another note, is the use of `node` in `start` script necessary in package.json since there is a shebang line on the generated ./bin/www file. I am not an expert on the subject. more insights on this would be appreciated.

**Comment by ionutale** [comment]
can you elaborate?
What is “shebang”?

**Comment by jilvin** [comment]
@ionutale Better refer to https://en.wikipedia.org/wiki/Shebang_(Unix) .

It seems windows don't support the shebang line. I am not sure. It works on my git bash(on windows) though.

**Comment by dougwilson** [comment]
Duplicate of https://github.com/expressjs/generator/issues/141

**Comment by jilvin** [comment]
@dougwilson Sorry for wasting your time. I thought it was a different discussion altogether judging by the heading of the issue. My bad. Apologies.

**Comment by jilvin** [comment]
> 
> 
> on another note, is the use of `node` in `start` script necessary in package.json since there is a shebang line on the generated ./bin/www file. I am not an expert on the subject. more insights on this would be appreciated.

@dougwilson Can you provide a little insight on this if possible? Kudos to your efforts.

**Comment by dougwilson** [comment]
No problem; do not feel like it was wasting my time :)

**Comment by dougwilson** [comment]
> Can you provide a little insight on this if possible?

Windows support

**Comment by jilvin** [comment]
Thanks a lot. Stay safe. Happy coding! 👍
