### ISSUE TITLE
Update mkdirp to avoid warnings on npm install

### ISSUE THREAD

**Issue by hanynathan** [expressjs/generator#263]
On npm i express-generator the following warning is shown:
npm WARN deprecated mkdirp@0.5.1: Legacy versions of mkdirp are no longer supported. Please update to mkdirp 1.x. (Note that the API surface has changed to use Promises in 1.x.)

**Comment by jonchurch** [comment]
mkdirp's 0.5.x line is getting very infrequent patches, so this can get bumped to either 0.5.5 exact, or `~0.5.5`. I'm surprised isaac released another patch after 0.5.4, and wouldn't expect to see anymore, but it seems he's flagging only the latest release on the 0.x line as non-deprecated.

The 1.x line states support for Node.js >= v10, which is out of range for Express's support threshold.

**Comment by IgorArnaut** [comment]
You should just update generator to use mkdirp 1.x.
