### ISSUE TITLE
express generator www file issue, remove http module dependency

### ISSUE THREAD

**Issue by huahuayu** [expressjs/generator#264]
when use express generator, in `/bin/www` there's code generated as below:
```js
/**
 * Create HTTP server.
 */

var server = http.createServer(app);

/**
 * Listen on provided port, on all network interfaces.
 */

server.listen(port);
server.on('error', onError);
server.on('listening', onListening);
```

I wonder why to create HTTP server from `http` module? and require it as a dependency `var http = require('http');`

why not use below code instead? Any difference?

```js
app.listen(port);
app.on('error', onError);
app.on('listening', onListening);
```

**Comment by dougwilson** [comment]
Hi @huahuayu there are three main reasons why it uses the `http` module directly:

1. Not using it does not remove the dependency, as `express` already has a dependency on the `http` module.
2. It shows users the pattern for how to use the module to wrap an app, which makes it easier to understand how to use `https` or web sockets.
3. Those events you listed do not fire on an `app` instance, only on the object that comes from the `http` module.

**Comment by huahuayu** [comment]
Thanks for your reply!
