### ISSUE TITLE
Should the node version < 6  be opted out in travis.yml ?

### ISSUE THREAD

**Issue by samsan1212** [expressjs/generator#275]
Hi all,

I have noticed the travis-ci has thrown error in this [job](https://travis-ci.org/github/expressjs/generator/jobs/647012868),
so I pulled the code from `master` branch, trying to see if the error also happens in the `master` branch.

According to the [job](https://travis-ci.org/github/expressjs/generator/jobs/647012868),

```bash
# node --version
v1.8.4
# npm --version
2.9.0
```

and the installation steps are:

```bash
# Skip updating shrinkwrap / lock
npm config set shrinkwrap false

# eslint for linting
# if [[ "$(cut -d. -f1 <<< "$TRAVIS_NODE_VERSION")" -lt 6 ]]; then
node -pe 'Object.keys(require("./package").devDependencies).join("\n")' | \
      grep -E '^eslint(-|$)' | \
      xargs npm rm --save-dev

# mocha for testing
# - use 3.x for Node.js < 4
# - use 5.x for Node.js < 6
npm install --save-dev mocha@3.5.3

# supertest for http calls
# - use 2.0.0 for Node.js < 4
# - use 3.4.2 for Node.js < 6
npm install --save-dev supertest@2.0.0

# Prune and rebuild node_modules
npm prune && npm rebuild

npm install
```

After the setup, we can try running the test

```bash
npm run test-ci
```

The test result showed there are 4 failed test cases, attached [test result log file](https://github.com/expressjs/generator/files/5006032/test.log)

![image](https://user-images.githubusercontent.com/15136948/89017530-05b65780-d34d-11ea-8083-e7e6b23fc4de.png)

Hence, should we opt out the old version of NodeJS and add the latest version of NodeJS into the `.travis.yml`?
(since the latest version of NodeJS version in the current `.travis.yml` is `9.11`)

i.e.
```yaml
language: node_js
node_js:
  - "6.16"
  - "7.10"
  - "8.17"
  - "9.11"
  - "10.22"
  - "11.15"
  - "12.18"
  - "13.14"
  - "14.7"
...
```

Besides, is it a good idea to encourage developers to use a newer NodeJS version in `package.json` ? i.e.

```json
{
  "name": "express-generator",
  ...
  "engines": {
    "node": ">= 6"
  },
  ...
}
```

**Comment by samsan1212** [comment]
Just found that there are PRs for fixing the travis-ci test issues ;p.

https://github.com/expressjs/generator/pull/265
https://github.com/expressjs/generator/pull/273

**Comment by dougwilson** [comment]
Yea, sorry, I will merge those PRs here soon. As for your quest the generator supports the same Node.js versions as Express.js does.

**Comment by samsan1212** [comment]
Thanks a lot. @dougwilson
