### ISSUE TITLE
Include .gitignore file as part of the initial project setup

### ISSUE THREAD

**Issue by yehee** [expressjs/generator#289]
Hi! I was wondering if there's any reason not to generate a simple `.gitignore` file as part of the initial project setup. A simple one that I could think of can include:
```
# See https://help.github.com/articles/ignoring-files/ for more about ignoring files.

# dependencies
/node_modules
/.pnp
.pnp.js

# testing
/coverage

# next.js
/.next/
/out/

# production
/build

# misc
.DS_Store
*.pem

# debug
npm-debug.log*
yarn-debug.log*
yarn-error.log*

# local env files
.env
.env.local
.env.development.local
.env.test.local
.env.production.local

# vscode settings
.vscode/
```

**Comment by dougwilson** [comment]
Hi @yehee ! Not everyone uses git for source control, so you need to opt in using a command line switch to indicate that you would like git-related artifacts generated. Just add `--git` as on of your command line arguments to the generator and you'll have a `.gitignore` added as part of the set up. I hope that helps!
