### ISSUE TITLE
Instructions on how to compile the css engines

### ISSUE THREAD

**Issue by blachawk** [expressjs/generator#291]
I successfully installed the express-generator on my local dev box, along with a css engine (sass). But I am failing to find any instructions on how to compile a sass file to css.  How do we go about that process?

**Comment by dougwilson** [comment]
The included engines do not require it to be compiled by any command is why; the middlewares will compile them on the fly as they are requested. The example page in the generated output will load up the css as an example for how to load the end result css from sass source.

**Comment by blachawk** [comment]
> The included engines do not require it to be compiled by any command is why; the middlewares will compile them on the fly as they are requested. The example page in the generated output will load up the css as an example for how to load the end result css from sass source.

Here are steps I took just to help me be on the same page with you...

* I installed the package through the terminal
* I then ran `$DEBUG=livereload:* npm start` 
* I then opened up my browser window and went to http://localhost:3000.  I can see the page.
* I then went back into my project and opened up style.scss and made a modification, and saved it.
* When I open up the style.css file it does not show the update.

What did I miss?

**Comment by blachawk** [comment]
oh, so there is not direct connection between the sass, and the .css file in the same directory?  ok, then that makes sense.  Is this process then left to me to figure out how to have them both talking to each other? or is there a setting I am missing to make that happen?

**Comment by dougwilson** [comment]
You have to restart the server after you edited the page, most likely. But I'm not familiar with all the different options, as folks contribute them as they like and we just merge them in. You can find the documentation for the SASS middleware here: https://www.npmjs.com/package/node-sass-middleware
