### ISSUE TITLE
Is express-generator is deprecated or out of maintenance?

### ISSUE THREAD

**Issue by 0xdw** [expressjs/generator#304]
The reason I'm asking is there are a couple of good features still in open issues for years. Like TypeScript Support, Test support, Bump Pug.js version etc. Are there any blockers to prevent merging these and improving the generator? I would love to contribute to this if it's moving forward.

**Comment by dougwilson** [comment]
Hi @0xdw apologies, as for a while, this was indeed EOL, as it was supposed to be replaced. But the replacement has stalled out so I actually am currently working on getting this project back up to speed. Any help is greatly appreciated! See #302 as well for some recent conversation.

**Comment by 0xdw** [comment]
@dougwilson Let's get this project back! Let me know if anything that I can help with. Even for the Express.js framework. :)

**Comment by IgorArnaut** [comment]
> Hi [@0xdw](https://github.com/0xdw) apologies, as for a while, this was indeed EOL, as it was supposed to be replaced. But the replacement has stalled out so I actually am currently working on getting this project back up to speed. Any help is greatly appreciated! See [#302](https://github.com/expressjs/generator/issues/302) as well for some recent conversation.
Dude, it's 2025 now.
