### ISSUE TITLE
Template injection in ejs reported by yarn audit

### ISSUE THREAD

**Issue by reporter123** [expressjs/generator#305]
The fallowing is reported by yarn audit:

┌───────────────┬──────────────────────────────────────────────────────────────┐
│ high          │ Template injection in ejs                                    │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ ejs                                                          │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ >=3.1.7                                                      │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ ejs                                                          │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ ejs                                                          │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://www.npmjs.com/advisories/1070256                     │
└───────────────┴──────────────────────────────────────────────────────────────┘

This is a potentially breaking change for users of ejs but only an already established code base need worry about that. I am will to do the foot work if such patch has no objection from you.

**Comment by dougwilson** [comment]
Hello, and thank you for reaching out. If you are trying to report a protentional security issue, please follow the procedure at http://expressjs.com/en/resources/contributing.html#security-policies-and-procedures . I already got what you posted above, of course. I will bring this up with the team to evaluate the issue and determine a path forward. Please feel free to reach out via email if you are interested in being kept in the loop or have any other concerns.

**Comment by reporter123** [comment]
With all due respect this is an already public issue not a newly found issue. I consider this to be an overzealous enforcement of your policy and will not be bother you again given this response.
