### ISSUE TITLE
express js fail, after npm start

### ISSUE THREAD

**Issue by szmarci** [expressjs/generator#31]
Hi,

I tried to run the generator, but run into some errors.
(I'm on OS X 10.9.2, node, npm, express, everything is the latest)
There are no problems until `npm start` I get this in the prompt:

```
> express@0.0.1 start /Users/szmarci/Sites/express
> node ./bin/www
```

Then I visit `http://localhost:3000/`, I get the Express test page (but unstyled) and immediately after this in the terminal:

```
GET / 304 982ms

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: spawn ENOENT
    at errnoException (child_process.js:998:11)
    at Process.ChildProcess._handle.onexit (child_process.js:789:34)

npm ERR! express@0.0.1 start: `node ./bin/www`
npm ERR! Exit status 8
npm ERR!
npm ERR! Failed at the express@0.0.1 start script.
npm ERR! This is most likely a problem with the express package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./bin/www
npm ERR! You can get their info via:
npm ERR!     npm owner ls express
npm ERR! There is likely additional logging output above.
npm ERR! System Darwin 13.1.0
npm ERR! command "node" "/usr/local/bin/npm" "start"
npm ERR! cwd /Users/szmarci/Sites/express
npm ERR! node -v v0.10.28
npm ERR! npm -v 1.4.9
npm ERR! code ELIFECYCLE
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/szmarci/Sites/express/npm-debug.log
npm ERR! not ok code 0
```

I couldn't find any solution with google, tried to sudo, change port, etc.. but no luck.

**Comment by carlosbaraza** [comment]
@renfeisong thank you.

Indeed, I had the same issue and was due to a missing installation of Compass. Just running `gem install compass` solved the issue.

Thanks!

**Comment by adc5** [comment]
I'm running Node.js on windows 8, and when I'm encountering the same/similar issue.  I follow these steps and it works perfectly until Iry :   
    C:\node\nodetest>npm start
    app.use.(function(req,res,next) {
    TypeError: Cannot read property 'use' of undefined
        at Object.<anonymous> {C:\node\nodetest\app.js:19:4)
        at Module._compile (module.js:460:26)
        at Object.Module._estiensions..js (module.js:478:10
        at Module.load (module.js:355:17)
        at require (module.js:365:17)
        at Object.<anonymous> (C:\node\nodetest\bin\www:7:11)
        at Module._compile (module.js:460:26)
        at Obeject.Module._extensions..js (module.js:478:10)

   npm ERR! Windows_NT 6.3.9600
   npm ERR! argv "C:\\Program Files\node.js\\\\node.exe" "C:\\Program Files\\node.js
   \\node_modules\\npm\\bin\\npm-cli.js" "start"
    npm ERR! node v0.12.2
    npm ERR! npm  v2.7.4
    npm ERR! ELIFECYCLE
    npm ERR!  nodetest@0.0.0 start 'node ./bin/www',
    npm ERR!  Exit status 1
    npm ERR!
    npm ERR! Failed at the nodetest@0.0.0 start script 'node./bin/www'
    npm This is most likely a problem with the nodetest package, not with npm itself

    AND this is my debug log:

    0 info it worked if it ends with ok
    1 verbose cli [ 'C:\\Program Files\\nodejs\\\\node.exe',
    1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
    1 verbose cli   'start' ]
    2 info using npm@2.7.4
    3 info using node@v0.12.2
    4 verbose node symlink C:\Program Files\nodejs\\node.exe
    5 verbose run-script [ 'prestart', 'start', 'poststart' ]
    6 info prestart nodetest3@0.0.0
    7 info start nodetest3@0.0.0
    8 verbose unsafe-perm in lifecycle true
    9 info nodetest3@0.0.0 Failed to exec start script
    10 verbose stack Error: nodetest3@0.0.0 start: `node ./bin/www`
    10 verbose stack Exit status 1
    10 verbose stack     at EventEmitter.<anonymous> (C:\Program   
     Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:213:16)
    10 verbose stack     at EventEmitter.emit (events.js:110:17)
    10 verbose stack     at ChildProcess.<anonymous> (C:\Program    
     Files\nodejs\node_modules\npm\lib\utils\spawn.js:14:12)
    10 verbose stack     at ChildProcess.emit (events.js:110:17)
    10 verbose stack     at maybeClose (child_process.js:1015:16)
    10 verbose stack     at Process.ChildProcess._handle.onexit (child_process.js:1087:5)
    11 verbose pkgid nodetest3@0.0.0
    12 verbose cwd C:\node\nodetest3
    13 error Windows_NT 6.3.9600
    14 error argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program         
     Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
    15 error node v0.12.2
    16 error npm  v2.7.4
    17 error code ELIFECYCLE
    18 error nodetest3@0.0.0 start: `node ./bin/www`
    18 error Exit status 1
    19 error Failed at the nodetest3@0.0.0 start script 'node ./bin/www'.
    19 error This is most likely a problem with the nodetest3 package,
    19 error not with npm itself.
    19 error Tell the author that this fails on your system:
    19 error     node ./bin/www
    19 error You can get their info via:
    19 error     npm owner ls nodetest3
    19 error There is likely additional logging output above.
    20 verbose exit [ 1, true ]

    
This is my app.js where the 'use' function is being called:

     var express = require('express');
     var path = require('path');
     var favicon = require('serve-favicon');
     var logger = require('morgan');
    var cookieParser = require('cookie-parser');
    var bodyParser = require('body-parser');

    var routes = require('./routes/index');
    var users = require('./routes/users');








    /// catch 404 and forwarding to error handler
    app.use(function(req, res, next) {
    var err = new Error('Not Found');
    err.status = 404;
    next(err);
    });

    /// error handlers

       // development error handler
       // will print stacktrace
        if (app.get('env') === 'development') {
        app.use(function(err, req, res, next) {
            res.status(err.status || 500);
            res.render('error', {
                message: err.message,
                error: err
            });
        });
    }


var app = express();

// view engine setup
app.set('views', path.join(__dirname, 'views'));
app.set('view engine', 'jade');

//
    app.use(favicon(__dirname + '/public/favicon.ico'));
    app.use(logger('dev')); 
    app.use(bodyParser.json());
    app.use(bodyParser.urlencoded());
    app.use(cookieParser());
    app.use(express.static(path.join(__dirname, 'public')));
 
    app.use('/', routes);
    app.use('/users', users);





    // production error handler
    // no stacktraces leaked to user
    app.use(function(err, req, res, next) {
        res.status(err.status || 500);
        res.render('error', {
            message: err.message,
            error: {}
        });
    });

I'm just getting 'into cmd'' and really enjoy it, so sorry if my syntax/phrasing or anything makes this impossible to sort through in order to give advice (this is my first post to github).

**Comment by dougwilson** [comment]
@adc5 you need to put the line `var app = express();` above when you first try to use the `app` variable (i.e. move that line above `/// catch 404 and forwarding to error handler`).

**Comment by adc5** [comment]
@dougwilson Thanks for that doug!  But when I call     npm start   it gives me  another set of errors:
    rfs.js.:797
        return binding.stat(pathModule._makeLong(path));
    Error:  ENOENT, no such file or directory 'filepath'
        at Error (native)
        at Object.fs.statsSync (fs.js:797:18)
        at favicon ('path to favicon')
        at Object.<anonymous> (C:\node\nodetest\app.js:49:9)   
        at Module._compile (module.js:460:26)
        at Object.Module._extensions..js (module.js:478:10)
        at Module.load (module.js:365:17)
        at Module.require (module.js.:365:17)
        at require (module.js:384:17)

And then the rest of the ERR! statements are the same.  Any other ideas?  Also,  is there a way to copy the text from node.js so I don't have to type it completely out each time?  Thanks again for the help!

**Comment by dougwilson** [comment]
@adc5 it's because you do not have a file at `/public/favicon.ico`. You either need to put one there, or comment out that line.

**Comment by adc5** [comment]
I tried that and it gave me:
    body-parser deprecated undefined extended option app.js
    C:\node\node\nodetest\bin\www:16  (line 16 is blank in app.js)
    aopp.set('port', port);

**Comment by adc5** [comment]
app.set('port',port);  
   
Sorry, accidently sent that while I was finishing it.  Could that mean I have a server connection issue>

**Comment by adc5** [comment]
and I forgot the @dougwilson : 2 previous posts

**Comment by dougwilson** [comment]
@adc5 I'm happy to help more, but please, let's stop filling the dozen people in this old thread's email inboxes. Please create a new issue here: https://github.com/expressjs/generator/issues/new
