### ISSUE TITLE
How to use axios?

### ISSUE THREAD

**Issue by ShineByPupil** [expressjs/generator#322]
```bash
npm i axios
```

```js
// routes/test.js

const express = require('express');
const router = express.Router();
const axios = require('axios');
const http = require('http');

router.get('/test1', (req, res) => {
  axios
    .get('https://jsonplaceholder.typicode.com/todos/1')
    .then((response) => {
      res.json(response.data);
    })
    .catch((error) => {
      console.error('Error fetching data:', error);
      res.status(500).json({ error: 'Error fetching data' });
    });
});

router.get('/test2', (req, res) => {
  const options = {
    hostname: 'jsonplaceholder.typicode.com',
    port: 80,
    path: '/todos/1',
    method: 'GET',
  };

  const request = http.request(options, (response) => {
    let data = '';

    response.on('data', (chunk) => {
      data += chunk;
    });

    response.on('end', () => {
      res.json(JSON.parse(data));
    });
  });

  request.on('error', (error) => {
    console.error('Error fetching data:', error);
    res.status(500).json({ error: 'Error fetching data' });
  });

  request.end();
});

module.exports = router;
```

我使用axios请求接口报错了。但是http模块能正常使用。错误信息：`The plain HTTP request was sent to HTTPS port`

I encountered an error when using axios to request an API. However, the HTTP module works fine. The error message is: `The plain HTTP request was sent to HTTPS port.`

**Comment by IamLizu** [comment]
Hi @ShineByPupil 👋 

I hope you are doing great. 

Your _test2_ is shows how to do the same thing as _test1_ but without using `axios`. So, if you plan **to use `axios`, you can simply remove _test2_ route**. 

Just so you know what's happening here, the host requires https, and in your _test1_ you are doing it correctly by requesting with `https://`. However, in _test2_ you are making the request with `http` which is giving you the error. You would need to replace that with `https` if you were to keep _test2_ route and it would have looked something like this,

```js
const https = require('https'); // Use 'https' instead of 'http'

// your other routes here

router.get('/test2', (req, res) => {
  const options = {
    hostname: 'jsonplaceholder.typicode.com',
    port: 443, // Use port 443 for HTTPS
    path: '/todos/1',
    method: 'GET',
  };

  const request = https.request(options, (response) => {
    let data = '';

    response.on('data', (chunk) => {
      data += chunk;
    });

    response.on('end', () => {
      res.json(JSON.parse(data));
    });
  });

  request.on('error', (error) => {
    console.error('Error fetching data:', error);
    res.status(500).json({ error: 'Error fetching data' });
  });

  request.end();
});
```

I hope that answers your question 🎉

**Comment by ShineByPupil** [comment]
Hi @IamLizu  👋

![img1](https://github.com/user-attachments/assets/dd8a96b4-814a-467f-893b-a05ebface44e)

![img2](https://github.com/user-attachments/assets/43d80caa-fe51-4211-b697-1a7b00a62703)

test2使用`http`是为了和`axios.get`做对比。`port`无论使用80（http），还是443（https）都没问题
我用二分法删除全部的干扰项，只剩`express-generator` + `axios`，刚好报错。
我没有使用`express-generator`脚手架，直接`nodejs` + `axios`，代码没有变化，能够正常运行

我的疑问是：`express-generator`和`axios`兼容吗？

test2 uses `http` to compare with `axios.get`. The `port` works fine whether using 80 (http) or 443 (https). 
I used a binary search method to remove all interference factors, leaving only `express-generator` + `axios`, and the error occurred.
I did not use the `express-generator` scaffolding; instead, I used `nodejs` + `axios`, and the code ran normally without any changes.

My question is: Are `express-generator` and `axios` compatible?

**Comment by ShineByPupil** [comment]
Hi @IamLizu 👋

```json
// package.json
{
  "scripts": {
    "start": "node ./bin/www"
  }
}
```

我又缩小了范围，我使用命令`npm run start`和`node ./bin/www`依次运行项目，得到了两个截然相反的结果。`node ./bin/www`直接运行的项目，axios能正常使用，符合预期。

I narrowed down the scope further. When I run the project using the command `npm run start `and then `node ./bin/www`, I get two completely opposite results. The project runs normally with `node ./bin/www`, and Axios works as expected.

![image](https://github.com/user-attachments/assets/9d564788-a9a0-4464-a891-ab8c79af3e0c)

![image](https://github.com/user-attachments/assets/c01264d8-5bf5-4239-88f2-c6b718df938c)

我第一次遇见这种问题，这太奇怪了

I've never encountered this kind of problem before; it's really strange.
