### ISSUE TITLE
change default template engine

### ISSUE THREAD

**Issue by defunctzombie** [expressjs/generator#47]
Should we change the default to something other than jade? Something like hbs will let users use html out of the box versus learning a new language.

Just an observation from some feedback on getting a new user going with express.

**Comment by outsideris** [comment]
hbs +1

**Comment by nicolasmccurdy** [comment]
I'm for keeping the default templating engine as Jade. Jade is simple (at least in my opinion), though it does have a bigger learning curve than just HTML alone. However, given how popular Jade is, how much it boosts productivity, and how fast and flexible it is, I think it's reasonable to encourage new users to use it. The `--ejs` option is still there if they aren't comfortable with Jade.

**Comment by defunctzombie** [comment]
I am closing this. We don't see to care enough and it probably doesn't matter enough.

**Comment by nicolasmccurdy** [comment]
:+1: I think it could help to simply add an extra note to the readme about how `--ejs` might be easier for beginners if they don't want to use a fancier templating language.
