### ISSUE TITLE
Add option --static to generate static index.html over specifying a view template engine

### ISSUE THREAD

**Issue by abepark01** [expressjs/generator#67]
I just wanted to run it by and see if it were okay to create a pull request for a --static option.
The use case is when I want to quickly generate an express project, but use it as a REST API only without using the views.

We create a static HTML file index.html and stick that into the public folder.
The same could be done for error.html.

The default route would just serve public/index.html.
I thought this it would be nice to not have to specify a view engine, but opt for static index.html.
I would love to work on this, but wanted to see if something like this would be acceptable.

Thanks!

**Comment by dougwilson** [comment]
This sounds fine to me, though for a rest API, why have a html file at all :)?

**Comment by abepark01** [comment]
Good point; I was thinking express would just be used to handle the REST API, but then the index.html in the public folder could be a boiler plate for a new single page app.

A lot of times, I would use the express generator and then create my own index.html in the public folder.
I would then modify the default route to serve public/index.html.

**Comment by nicolasmccurdy** [comment]
:+1: I worked on a simple Express app where I realized that all of my views should be dynamic (updating via AJAX calls), so I switched from rendering templates on the server side with express to hosting an API and using the static middleware to host a static HTML client for that API using AngularJS. I really liked the setup, and I think it's a fantastic idea to add support for this kind of project to the generator (especially considering movements to microservices and more and more fancy AJAX web apps).

**Comment by cameronjroe** [comment]
+1

**Comment by smithb1994** [comment]
+1

**Comment by veggiemonk** [comment]
+1 
Why is it not merged yet?

**Comment by dougwilson** [comment]
So back months ago, something happened to the repo and destroyed the PRs. I asked for them to be re-opened, many were, and we have since merged in most of them. The PR (https://github.com/expressjs/generator/pull/68#issuecomment-229780046) for this hasn't been re-opened for months, so please, someone go ahead and get us the PR back and we're here these days to actually merge :) No reason to really keep the issue open, though, as a PR being opened will help us track it.
