### ISSUE TITLE
haml support

### ISSUE THREAD

**Issue by dotnetCarpenter** [expressjs/generator#71]
please :rainbow:, haml as view engine.

**Comment by dougwilson** [comment]
SGTM :) I marked "help wanted" for someone who knows more about haml to contribute :)

**Comment by dotnetCarpenter** [comment]
NTFY @carbureted

**Comment by dougwilson** [comment]
I haven't seen a PR come in and no real reason to keep this issue open indefinitely. Anyone coming across this issue, please feel free to open a PR :)
