### ISSUE TITLE
Make instructions more cmd.exe-friendly

### ISSUE THREAD

**Issue by simonjosefsson** [expressjs/generator#73]
After the generator has created a project, it displays this message:

    run the app:
      $ DEBUG=myapp:* ./bin/www

Which is a bit cryptic for *nix beginners (I know it tripped me up)

Why not suggest ```npm start``` instead since it's already included in package.json?
(With maybe a separate note about setting the DEBUG environment variable)

**Comment by dougwilson** [comment]
You mean `cmd.exe`-friendly :) I use Windows all the time and use bash on it.

**Comment by simonjosefsson** [comment]
touché :wink: 

I think the point still stands that for new Windows users, running the generator for the first time will be a confusing experience. And perhaps detrimentally influencing the impression of express itself (however wrongly deserved)

**Comment by dougwilson** [comment]
lol. But yes, it'll definitely be fixed, especially since I literally _only_ use Windows. It's also why we do Express CI on Windows, even.
