### ISSUE TITLE
Question: why the `bin` folder and `www` file?

### ISSUE THREAD

**Issue by dstroot** [expressjs/generator#74]
Just curious why the app is structured that way?  Most express apps/tutorials don't break the app up into two parts like this.  Would love to get why this is a "best practice" as built by the generator.  Thanks!

**Comment by dougwilson** [comment]
Hi @dstroot ! So I'm about to head out for the night, but to get you at least something right away, I believe there was a previous discussion over in #25 . Let me know if it happened to answer your question or even if you have new ones! I'll be looking for your response :)

**Comment by dstroot** [comment]
@dougwilson this was exactly what I was looking for.  I guess my search-fu took a day off.  Closing this one.  Thanks as always!

**Comment by dougwilson** [comment]
No problem!
