### ISSUE TITLE
Remove hogan (hjs) option

### ISSUE THREAD

**Issue by cmawhorter** [expressjs/generator#77]
hjs seems to be effectively dead: https://github.com/nullfirm/hjs/issues/2#issuecomment-47050776

I have no alternative to suggest but the documentation still references express 3.0 and it could be confusing once 3.0 is deprecated.

**Comment by dougwilson** [comment]
Sounds fine. We can remove in the next major version (5) unless anyone objects.

**Comment by barryclark** [comment]
I'd still appreciate a hogan or handlebars option in the generator. 

Is there a reason why https://github.com/nullfirm/hjs/ was used instead of the more maintained  https://github.com/twitter/hogan.js/ ?

**Comment by dougwilson** [comment]
So in all this time, no one has ever really chimed in on this, and we have a test that continues to pass with the current hjs and Express 4.x, so unless there is some really good reason, I don't see any real reason for the removal unless it stops working with Express (and ideally our tests should tell us when that happens). ¯\_(ツ)_/¯
