### ISSUE TITLE
Remove app.set('port', port); in express generator 4

### ISSUE THREAD

**Issue by superclarkk** [expressjs/generator#81]
Setting the port, like, [`app.set('port', port)](https://github.com/expressjs/generator/blob/master/templates/js/www#L16), is not supported in express 4, so should be removed.

**Comment by dougwilson** [comment]
Can you explain how is it not supported in Express 4? Settings are just a bag of whatever you want.

**Comment by superclarkk** [comment]
How is it utilised in the generated app? At the very least, it's superfluous.

**Comment by dougwilson** [comment]
It's just a very common convention to know what port your app is on to provide links in your layouts. Adding that makes `{{port}}` available in your layouts automatically, so you can do `<a href="http://localhost:{{port}}/blah">` and it'll work for your development.

**Comment by hal-gh** [comment]
I appreciate that, but it needs to either be used for something in the app, an explanation given on why it has been included, or omitted altogether. The generator is often a new user's first example of a working app. Anything in it that they don't understand can be very off-putting.

**Comment by dougwilson** [comment]
It was only added after tons and tons of requests for it; I'm not going to remove it and go through that again. If there is a PR you want to make to add more information to this line, or use it somewhere in the app, that would be accepted :)
