### ISSUE TITLE
Add switch --nunjucks to add the Nunjucks template engine

### ISSUE THREAD

**Issue by kruncher** [expressjs/generator#87]
This is by far my favorite template engine and it would be pretty sweet if this generator could automatically wire this up as the default template engine.

https://mozilla.github.io/nunjucks/

It is pretty simple to configure express.js to use nunjucks:

```javascript
var app = express();

nunjucks.configure('views', {
    autoescape: true,
    express: app
});

app.get('/', function(req, res) {
    res.render('index.html');
});
```
(above snippet taken from https://mozilla.github.io/nunjucks/getting-started.html)

**Comment by dougwilson** [comment]
SGTM. Would you be willing to put together a PR? It should be pretty straight-forward.

**Comment by dougwilson** [comment]
Hi @kruncher a PR was created to do this, but when I reviewed it and dig into it, I found the following things (from #119):

> I was also just browsing their issues and it looks like they don't really want to deal with the Express.js integration anyway: mozilla/nunjucks#611
