### ISSUE TITLE
AppVeyor fails by default

### ISSUE THREAD

**Issue by jordi12100** [expressjs/generator#94]
See: https://ci.appveyor.com/project/dougwilson/generator/build/123

Last 2 fail because the dependency can't be found.

**Comment by dougwilson** [comment]
I have noticed that this happens randomly within certain versions. There much be something up with the AppVeyor environment. If you can help investigate, that would be awesome!

**Comment by jordi12100** [comment]
I tried to look into this today, but I couldn't find a solution. 
AppVeyor tests on a Windows VM, so that may be the cause.

I'm on Mac/ Unix env so I can't test if these node versions are broken on windows, or require a different setting.

Since most servers and a lot of developers are on Unix, why not switch to Travis. I think it's important so that no broken builds get merged with the master. What do you think?

**Comment by gokaygurcan** [comment]
+1 for Travis. It's a well known CI tool and easier to setup. 

But first, I guess we should ask that is there any reason to choose AppVeyor in the first place? Or, it was just random thing?

**Comment by dougwilson** [comment]
Um, I'm not sure where you guys are looking, but we have been using Travis CI this whole time, there is even a badge on the README for Travis CI.

**Comment by dougwilson** [comment]
We run on AppVeyor because, since this is a command line tool that does file system operations, we need to ensure that the tool works on the environments where developers work, like Linux and Windows. If there is a CI that offers Mac OS X CI, we'd jump on that as well.

**Comment by Fishrock123** [comment]
We might be able to use the Node.js CI. It has everything from Windows to PPC BE Fedora. XD

**Comment by Fishrock123** [comment]
https://ci.nodejs.org/computer/ --- it might be private right now for security-related reasons though.

**Comment by asimpletune** [comment]
Hey, I showed this to the appveyor folks and they fixed it! Check it [out!](http://help.appveyor.com/discussions/problems/4770-node-versions-202-and-234-x86-not-found)

I ran a little base test of my own and it seems to be no longer failing at the same place. With that said, now there're issues with npm installing dependencies, but hey it's an improvement!

**Comment by dougwilson** [comment]
I have investigated this issue and determined the cause: something is causing various `npm_config_*` environment variables to be the string `undefined` when the test is invoked, and that is carried down into the secondary npm invocations.
